import * as React from 'react';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://127.0.0.1:8000';
type Auth = { access_token: string; user: { user_id: string; email: string; role: string } };
type Recipient = { recipient_id: string; name: string; private_key?: string; active?: boolean };
type Document = { document_id: string; name: string; document_hash: string };
type Message = { message_id: string; document_name: string; transaction_id: string; sent_at: string; expires_at?: string | null };
type Chain = { chain_valid: boolean; quorum: number; validator_count: number; validators: { validator: string; online: boolean; entries: number; head: string }[] };
type Page = 'chats' | 'documents' | 'blockchain' | 'admin' | 'forensics';

function encode(bytes: Uint8Array) { let binary = ''; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }

function App() {
  const [auth, setAuth] = React.useState<Auth | null>(() => JSON.parse(localStorage.getItem('cryptatrace-auth') || 'null'));
  const [page, setPage] = React.useState<Page>('chats');
  const [mode, setMode] = React.useState<'login' | 'register'>('login');
  const [recipients, setRecipients] = React.useState<Recipient[]>([]);
  const [documents, setDocuments] = React.useState<Document[]>([]);
  const [chain, setChain] = React.useState<Chain | null>(null);
  const [selected, setSelected] = React.useState<Recipient | null>(null);
  const [messages, setMessages] = React.useState<Message[]>([]);
  const [payload, setPayload] = React.useState('');
  const [message, setMessage] = React.useState('Select a recipient and attach a classified document.');
  const [verified, setVerified] = React.useState<boolean | null>(null);
  const [busy, setBusy] = React.useState(false);

  async function request(path: string, options: RequestInit = {}) { const headers = new Headers(options.headers); headers.set('Content-Type', 'application/json'); if (auth) headers.set('Authorization', `Bearer ${auth.access_token}`); const response = await fetch(`${API}${path}`, { ...options, headers }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Operation failed'); return data; }
  async function refresh() { if (!auth) return; try { const [r, d, c] = await Promise.all([request('/api/v1/recipients'), request('/api/v1/documents'), request('/api/v1/ledger/status')]); const keys = JSON.parse(localStorage.getItem(`cryptatrace-recipient-keys-${auth.user.user_id}`) || '{}'); const hydrated = r.map((item: Recipient) => ({ ...item, private_key: keys[item.recipient_id] })); setRecipients(hydrated); setDocuments(d); setChain(c); if (!selected && hydrated[0]) setSelected(hydrated[0]); } catch (error) { setMessage(error instanceof Error ? error.message : 'Workspace unavailable.'); } }
  React.useEffect(() => { void refresh(); }, [auth]);
  React.useEffect(() => { if (selected) void request(`/api/v1/conversations/${selected.recipient_id}`).then(setMessages).catch(() => setMessages([])); }, [selected]);

  async function authenticate(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { const data = await request(`/api/v1/auth/${mode}`, { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); setAuth(data); localStorage.setItem('cryptatrace-auth', JSON.stringify(data)); setMessage('Identity verified.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Authentication failed.'); } finally { setBusy(false); } }
  async function addRecipient(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { const data = await request('/api/v1/recipients', { method: 'POST', body: JSON.stringify({ name: form.get('name') }) }); const keys = JSON.parse(localStorage.getItem(`cryptatrace-recipient-keys-${auth?.user.user_id}`) || '{}'); keys[data.recipient_id] = data.private_key; localStorage.setItem(`cryptatrace-recipient-keys-${auth?.user.user_id}`, JSON.stringify(keys)); setRecipients((items) => [...items, data]); setSelected(data); setMessage(`${data.name} is ready to receive documents.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not add recipient.'); } finally { setBusy(false); } }
  async function sendFile(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('file'); if (!(file instanceof File) || !file.size || !selected?.private_key) { setMessage('Choose a recipient with a browser-held key and attach a document.'); return; } setBusy(true); try { const document = await request('/api/v1/documents', { method: 'POST', body: JSON.stringify({ name: file.name, content_base64: encode(new Uint8Array(await file.arrayBuffer())) }) }); const expiry = String(form.get('expires_at') || ''); const delivery = await request(`/api/v1/documents/${document.document_id}/decrypt`, { method: 'POST', body: JSON.stringify({ recipient_id: selected.recipient_id, private_key: selected.private_key, expires_at: expiry ? new Date(Date.now() + Number(expiry) * 86400000).toISOString() : null }) }); setPayload(delivery.content_base64); setVerified(null); setMessage(`Sent ${file.name}. Ledger transaction ${delivery.ledger_transaction_id} committed.`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Document sharing failed.'); } finally { setBusy(false); } }
  async function revokeRecipient() { if (!selected) return; setBusy(true); try { await request(`/api/v1/recipients/${selected.recipient_id}/revoke`, { method: 'POST' }); setMessage(`${selected.name}'s access was revoked and recorded on the ledger.`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Revocation failed.'); } finally { setBusy(false); } }
  async function verify(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const content = String(new FormData(event.currentTarget).get('content') || payload); setBusy(true); try { const data = await request('/api/v1/forensics/verify', { method: 'POST', body: JSON.stringify({ content_base64: content }) }); setVerified(data.match); setMessage(data.match ? `Verified recipient: ${data.recipient.name}.` : 'Tamper detected: payload hash does not match the ledger.'); } catch (error) { setVerified(false); setMessage(error instanceof Error ? error.message : 'Verification failed.'); } finally { setBusy(false); } }
  async function exportLedger() { try { const data = await request('/api/v1/ledger/export'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); link.download = 'cryptatrace-ledger-export.json'; link.click(); URL.revokeObjectURL(link.href); } catch (error) { setMessage(error instanceof Error ? error.message : 'Ledger export failed.'); } }
  async function downloadDocument(documentId: string) { try { const data = await request(`/api/v1/documents/${documentId}/download`); const binary = atob(data.content_base64); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([bytes])); link.download = data.name; link.click(); URL.revokeObjectURL(link.href); } catch (error) { setMessage(error instanceof Error ? error.message : 'Document download failed.'); } }
  function logout() { localStorage.removeItem('cryptatrace-auth'); setAuth(null); setSelected(null); }

  if (!auth) return <Auth mode={mode} busy={busy} message={message} onSubmit={authenticate} onToggle={() => setMode(mode === 'login' ? 'register' : 'login')} />;
  return <main className="app-shell"><aside className="rail"><Brand /><nav><Nav active={page === 'chats'} label="Chats" onClick={() => setPage('chats')} /><Nav active={page === 'documents'} label="Documents" onClick={() => setPage('documents')} /><Nav active={page === 'blockchain'} label="Blockchain" onClick={() => setPage('blockchain')} /><Nav active={page === 'forensics'} label="Forensics" onClick={() => setPage('forensics')} />{auth.user.role === 'admin' && <Nav active={page === 'admin'} label="Admin" onClick={() => setPage('admin')} />}</nav><div className="rail-bottom"><span className="pulse" /> OFFLINE / ENCRYPTED<small>{auth.user.role.toUpperCase()} ACCESS</small><button className="logout" onClick={logout}>Sign out</button></div></aside><section className="content"><header className="topbar"><div><p className="eyebrow">CRYPTATRACE / PRIVATE DOCUMENT NETWORK</p><h1>{page === 'chats' ? 'Classified conversations.' : page === 'documents' ? 'Document vault.' : page === 'blockchain' ? 'Blockchain status.' : page === 'admin' ? 'Administration.' : 'Forensic verification.'}</h1></div><div className="operator"><span className="pulse" /> {auth.user.email}</div></header>{page === 'chats' && <Chats recipients={recipients} selected={selected} messages={messages} onSelect={setSelected} onAdd={addRecipient} onSend={sendFile} onRevoke={revokeRecipient} busy={busy} message={message} />}{page === 'documents' && <section className="page-grid"><div className="wide-panel"><span className="eyebrow">PRIVATE VAULT</span><h2>Registered documents</h2><p>Original document hashes are indexed here before protected delivery.</p><button className="compact-button" onClick={() => void refresh()}>Refresh vault</button><div className="document-grid">{documents.length ? documents.map((doc) => <article className="document-card" key={doc.document_id}><strong>{doc.name}</strong><small>{doc.document_id}</small><code>{doc.document_hash}</code><button className="compact-button" onClick={() => void downloadDocument(doc.document_id)}>Download original</button></article>) : <p className="empty">No documents uploaded yet.</p>}</div></div></section>}{page === 'blockchain' && <Blockchain chain={chain} onRefresh={refresh} />}{page === 'forensics' && <Forensics payload={payload} verified={verified} message={message} busy={busy} onVerify={verify} />}{page === 'admin' && <Admin chain={chain} documents={documents} recipients={recipients} onExport={exportLedger} />}</section></main>;
}

function Brand() { return <div className="brand"><span className="brand-mark">C</span><span>CryptaTrace<small>PRIVATE DOCUMENT NETWORK</small></span></div>; }
function Nav({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) { return <button className={active ? 'active' : ''} onClick={onClick}>{label}</button>; }
function Auth({ mode, busy, message, onSubmit, onToggle }: { mode: 'login' | 'register'; busy: boolean; message: string; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onToggle: () => void }) { return <main className="auth-shell"><div className="auth-art"><Brand /><div><p className="eyebrow">CLASSIFIED COMMUNICATIONS</p><h1>Share securely.<br /><em>Trace precisely.</em></h1><p className="auth-copy">Private conversations for classified documents, backed by recipient-bound delivery evidence.</p></div><p className="auth-proof">CHAIN / 2 OF 3<br /><span>Authorized access becomes evidence.</span></p></div><section className="auth-panel"><span className="eyebrow">{mode === 'login' ? 'RETURNING OPERATOR' : 'NEW OPERATOR'}</span><h2>{mode === 'login' ? 'Sign in to CryptaTrace' : 'Create your operator account'}</h2><p>The first account on this offline node becomes admin.</p><form onSubmit={onSubmit}><label>Email<input name="email" type="email" placeholder="operator@cryptatrace.local" required /></label><label>Password<input name="password" type="password" minLength={8} placeholder="Minimum 8 characters" required /></label><button disabled={busy}>{busy ? 'Working...' : mode === 'login' ? 'Open workspace' : 'Create account'} <span>→</span></button></form><p className="auth-error">{message.includes('failed') || message.includes('exists') ? message : ''}</p><button className="text-button" onClick={onToggle}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></section></main>; }
function Chats({ recipients, selected, messages, onSelect, onAdd, onSend, onRevoke, busy, message }: { recipients: Recipient[]; selected: Recipient | null; messages: Message[]; onSelect: (recipient: Recipient) => void; onAdd: (event: React.FormEvent<HTMLFormElement>) => void; onSend: (event: React.FormEvent<HTMLFormElement>) => void; onRevoke: () => void; busy: boolean; message: string }) { return <section className="chat-layout"><aside className="contact-list"><span className="eyebrow">RECIPIENTS / {recipients.length}</span>{recipients.map((item) => <button className={selected?.recipient_id === item.recipient_id ? 'contact active' : 'contact'} key={item.recipient_id} onClick={() => onSelect(item)}><span className="avatar">{item.name[0]}</span><span><b>{item.name}</b><small>{item.active === false ? 'Access revoked' : 'Secure channel ready'}</small></span></button>)}<form className="new-contact" onSubmit={onAdd}><input name="name" placeholder="Add recipient" required /><button disabled={busy}>+</button></form></aside><div className="conversation"><header className="conversation-head"><strong>{selected?.name || 'Select a secure conversation'}</strong><small>{selected ? selected.active === false ? 'ACCESS REVOKED' : 'VERIFIED RECIPIENT' : 'Attachments are committed on send'}</small>{selected && selected.active !== false && <button className="revoke-button" type="button" onClick={onRevoke}>Revoke access</button>}</header><div className="message-space"><div className="encryption-note">LOCKED CHANNEL<br /><span>Attachments are fingerprinted and committed to the offline chain.</span></div>{messages.map((item) => <div className="message-bubble" key={item.message_id}><small>{item.document_name} · {new Date(item.sent_at).toLocaleString()}</small><p>Protected copy committed as {item.transaction_id}.</p>{item.expires_at && <small>Expires {new Date(item.expires_at).toLocaleString()}</small>}</div>)}<div className="message-bubble"><small>DELIVERY STATUS</small><p>{message}</p></div></div><form className="composer" onSubmit={onSend}><label className="file-drop"><input type="file" name="file" required /><b>Attach classified document</b><small>Any file type · watermark and ledger commitment applied</small></label><label className="expiry-field">Expires in days<input name="expires_at" type="number" min="1" max="365" placeholder="30" /></label><button disabled={busy || !selected || selected.active === false || !selected.private_key}>{busy ? 'Committing...' : 'Send securely'} <span>↑</span></button></form></div></section>; }
function Blockchain({ chain, onRefresh }: { chain: Chain | null; onRefresh: () => Promise<void> }) { return <section className="page-grid"><div className="wide-panel"><span className="eyebrow">PERMISSIONED OFFLINE DLT</span><h2>Current chain status</h2><p>Three local validator logs replicate every classified-document delivery. Two matching validators are required.</p><button className="compact-button" onClick={() => void onRefresh()}>Refresh status</button><div className={`chain-banner ${chain?.chain_valid ? 'good' : 'bad'}`}>{chain?.chain_valid ? 'CHAIN VALID / QUORUM REACHED' : 'CHAIN WAITING FOR COMMITMENT'}<span>{chain ? `${chain.quorum} / ${chain.validator_count} validators` : ''}</span></div><div className="validator-grid">{chain?.validators.map((validator) => <article key={validator.validator}><strong>{validator.validator}</strong><b>{validator.online ? 'ONLINE' : 'OFFLINE'}</b><small>{validator.entries} blocks · {validator.head.slice(0, 18)}...</small></article>)}</div></div></section>; }
function Forensics({ payload, verified, message, busy, onVerify }: { payload: string; verified: boolean | null; message: string; busy: boolean; onVerify: (event: React.FormEvent<HTMLFormElement>) => void }) { return <section className="page-grid"><div className="wide-panel"><span className="eyebrow">FORENSIC LABORATORY</span><h2>Inspect a surfaced copy</h2><p>Recompute the delivered-byte hash and compare it with the signed chain event.</p><form onSubmit={onVerify}><textarea name="content" defaultValue={payload} placeholder="Paste fingerprinted base64 payload" required /><button disabled={busy}>{busy ? 'Inspecting...' : 'Extract and verify'} <span>→</span></button></form><div className={`result-banner ${verified === true ? 'good' : verified === false ? 'bad' : ''}`}>{verified === true ? 'MATCH CONFIRMED' : verified === false ? 'INTEGRITY FAILURE' : 'NO INSPECTION YET'}<span>{message}</span></div><div className="photo-note"><strong>Photographed pages</strong><p>Reliable camera-photo identification needs a robust image watermarking adapter that survives perspective, lighting, resizing, and compression. The current file watermark must not claim that capability.</p></div></div></section>; }
function Admin({ chain, documents, recipients, onExport }: { chain: Chain | null; documents: Document[]; recipients: Recipient[]; onExport: () => void }) { return <section className="page-grid"><div className="wide-panel"><span className="eyebrow">ADMINISTRATION</span><h2>Node control center</h2><p>Manage the local CryptaTrace node and observe its permissioned validator network.</p><button className="compact-button" onClick={onExport}>Export ledger evidence</button><div className="admin-stats"><article><strong>{documents.length}</strong><small>Documents</small></article><article><strong>{recipients.length}</strong><small>Recipients</small></article><article><strong>{chain?.validators.filter((item) => item.online).length || 0} / {chain?.validator_count || 3}</strong><small>Validators online</small></article></div><div className="admin-warning"><strong>Production boundary</strong><p>This is an offline DLT adapter. Production requires separate validator authorities and audited ML-DSA/ML-KEM providers.</p></div></div></section>; }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
